
services:
  sqlite:
    container_name: sqliteDB
    restart: always
    env_file: ../.env
    build:
      context: ./sqlite
      dockerfile: Dockerfile
    volumes:
      - sqlite-vol:/data
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "sqlite3 /data/database.sqlite 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  backend:
    container_name: backend
    restart: always
    env_file: ../.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - sqlite-vol:/data
    networks:
      - transcendence
    depends_on:
      redis:
        condition: service_started
      sqlite:
        condition: service_healthy
    ports:
      - "8080:8080"

  game_server:
    container_name: game_server
    build:
      context: ./game_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - transcendence
    depends_on:
      backend:
        condition: service_started
    env_file: ../.env

  # frontend:
  #   container_name: frontend
  #   restart: always
  #   env_file: ../.env
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - transcendence
  #   depends_on:
  #     - backend

  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - transcendence

volumes:
  sqlite-vol:
    name: transcendence_sqlite_db
    driver_opts:
      type: none
      #device: /home/transcendence/Desktop/Data/sqlite-data
      device: /home/gude-cas/ft_transcendence/sqlite-data
      o: bind

networks:
  transcendence:
    name: transcendence

